# Generated by Django 5.1.2 on 2024-11-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_author_question_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='like_counter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_counter',
        ),
    ]
